//! The `Kaon` VM and runtime.
//! 
//! The [Vm] (_virtual machine_) is stack-based; values are pushed and 
//! popped from a stack. It runs the bytecode generated by the compiler.

pub mod stack;
pub mod stdio;
pub mod trace;
pub mod vm;

pub use stack::{Frame, Stack};
pub use stdio::{KaonStderr, KaonStdin, KaonStdout};
pub use trace::Trace;
pub use vm::{Vm, VmSettings, VmContext};
