[package]
name = "kaon_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaon = { path="../kaon" }
kaon_fmt = { path="../kaon-fmt" }
rustyline = "9.0.0"
clap = "3.1.2"
termcolor = "1.1.2"